@echo off
cd %~dp0
chcp 1251 > nul
setlocal EnableDelayedExpansion

if "%1"=="/q" (
	set qMode=1
	shift /1
	echo %1
)
if "%1"=="/n" (
	set nologo=1
	shift /1
)
if "%1"=="/t" (
	set ndt=1
	shift /1
)

set "cmd=%1"
shift /1

if not "%nologo%"=="1" (
	call :echo "CAB Manager 1.0"
	call :echo .
)

if "%cmd%"=="help" (
	call :echo "Справка по CAB Manager"
	call :echo "."
	call :echo "CABMGR [/Q] [/N] [/T] HELP/EXTRACT/CREATE cabfile folder"
	call :echo "."
	call :echo "/Q        Отключает вывод текста в консоль."
	call :echo "/N        Отключает вывод сообщения о версии CAB Manager."
	call :echo "/T        Отключает удаление временных файлов."
	call :echo "HELP      Показывает этот текст."
	call :echo "EXTRACT   Распаковывает CAB-архив cabfile в папку folder."
	call :echo "CREATE    Создает CAB-архив cabfile из файлов в папке folder."
) else if "%cmd%"=="extract" (
	if "%1"=="" (
		call :echo "ОШИБКА: Параметры не заданы"
		exit /b 1
	)
	if "%2"=="" (
		call :echo "ОШИБКА: Параметры не заданы"
		exit /b 1
	)
	call :echo "Извлечение архива %1..."
	if not exist "%2" mkdir "%2"
	expand "%1" -f:* "%2" > nul
	if "%errorlevel%"=="0" (
		call :echo "Архив %1 успешно извлечён в %2"
	) else (
		call :echo "Ошибка извлечения архив %1. Код: %errorlevel%"
	)
) else if "%cmd%"=="create" (
	if "%1"=="" (
		call :echo "ОШИБКА: Параметры не заданы"
		exit /b 1
	)
	if "%2"=="" (
		call :echo "ОШИБКА: Параметры не заданы"
		exit /b 1
	)
	call :echo "Создание архива %1..."
	call :echo "Создание файла конфигурации..."
	
	echo ;Generated by CAB Manager > "%temp%\%1.txt"
	echo .OPTION EXPLICIT >> "%temp%\%1.txt"
	echo .Set CabinetNameTemplate=%1 >> "%temp%\%1.txt"
	echo .Set Cabinet=on >> "%temp%\%1.txt"
	echo .Set Compress=on >> "%temp%\%1.txt"
	echo .Set MaxDiskSize=cdrom >> "%temp%\%1.txt"
	echo .Set ClusterSize=cdrom >> "%temp%\%1.txt"
	echo .Set DiskDirectoryTemplate= ; >> "%temp%\%1.txt"
	for /f "usebackq tokens=*" %%i in (`where * /r %2`) do echo "%%i" >> "!temp!\%1.txt"
	
	call :echo "Выполнение MAKECAB..."
	makecab /f "%temp%\%1.txt" > nul
	
	if not "%ndt%"=="1" (
		del "%temp%\%1.txt"
		del setup.inf
		del setup.rpt
	)
	
	if "%errorlevel%"=="0" (
		call :echo "Архив %1 успешно создан."
	) else (
		call :echo "Ошибка создания архива. Код: %errorlevel%"
	)
) else (
	call :echo "Использование: CABMGR [/Q] [/N] [/T] HELP/EXTRACT/CREATE cabfile folder"
)

exit /b 0

:echo
	if not "%qMode%"=="1" (
		if "%~1"=="." ( echo. ) else ( echo %~1 )
	)
exit /b

endlocal